# Generated by Django 5.2.7 on 2025-10-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('rooms', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('hotelImage', models.CharField(max_length=255)),
            ],
        ),
    ]
